import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';

const prod = process.argv[2] === 'production';
const context = await esbuild.context({
	banner: {
		js: `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
Source: https://github.com/zacharyyamaoka/obsidian-external-file-bridge
*/`,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	platform: 'node',
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins,
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
});

if (prod) {
	await context.rebuild();
	await context.dispose();
} else {
	await context.watch();
}
